export const COUNTER_ADD = "COUNTER_ADD";
export const COUNTER_SUBTRACT = "COUNTER_SUBTRACT";

export const USERS_ADD = "USERS_ADD";
export const USERS_MODIFY = "USERS_MODIFY";

export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";